@baseURL = http://localhost:3333

# @name create-org
POST {{baseURL}}/signup
Content-Type: application/json

{
  "name": "Test Org",
  "email": "test@org.com",
  "password": "testpassword",
  "phone": "1234567890",
  "zip": "12345",
  "address": "123 Test St",
  "city": "Test City",
  "state": "TS",
  "country": "Test Country"
}
###

# @name authenticate-org
POST {{baseURL}}/signin
Content-Type: application/json

{
  "email": "test@org.com",
  "password": "testpassword"
}
###

# @name create-pet
POST {{baseURL}}/pet
Content-Type: application/json

{
  "name": "Test pet",
  "orgID": "bb0c3c63-4e46-4c80-bf17-13181100b3eb",
  "description": "A friendly test pet",
  "age": "PUPPY",
  "energyLevel": "HIGH",
  "size": "SMALL",
  "independenceLevel": "VERY_DEPENDENT",
  "environmentSize": "LARGE"
}
###

# @name fetch-pets-by-city
GET {{baseURL}}/pets?age=PUPPY